### ISSUE TITLE
nice, do you want this to be an extension too?

### ISSUE THREAD

**Issue by ClashSAN** [Zyin055/Config-Presets-Script-OLD-#1]
this is a heavily requested feature, wonderful news ty!
It works great, you may also want to make an extension version for those that never checkout custom scripts, and want one-click installation. If you install your repo through "install from url" in webui, since your custom script is already in a folder called `scripts`, it will show up as a selectable custom script. Many custom scripts eg: [pixel_art.py](https://github.com/C10udburst/stable-diffusion-webui-scripts/blob/master/pixel_art/pixel_art.py) work in extensions.

you will need to change the .json location path in order for it to work as an extension.

**Comment by Zyin055** [comment]
I hadn't looked into using an extension because a script was able to do most of what I wanted, but now looking at the wiki page on custom extensions it looks like that would indeed be a better fit since it'd let me inject Javascript onto the page, which is something I couldn't figure out how to do with a script no matter how hard I tried.

If I do convert this into an extension, why would the .json file need to move?

Also, please please please add `elem_id` to the UI components/rows so that Javascript can select them more easily! Currently I'm doing some janky ass shit to select the elements I need, meaning it only works in English.

**Comment by ClashSAN** [comment]
>Also, please please please add elem_id to the UI components/rows so that Javascript can select them more easily! Currently I'm doing some janky ass shit to select the elements I need, meaning it only works in English.

I'm pretty sure auto prefers you PR those small changes necessary for the extension, so you can have the tools you need, so go ahead :+1: 

>If I do convert this into an extension, why would the .json file need to move?

I just mean your extension files would be in `stable-diffusion-webui\extensions\Config-Presets\scripts`
and you would just need to make config_presets.json work in that location.

(You could also move files to the scripts folder, as Prompt-Gallery does in their install.py  but it may be disorderly and break people's previous configuration?)

**Comment by Zyin055** [comment]
I converted the script into an extension, but one thing I can't figure out how to do is to hide my "Config Presets" value in the Scripts dropdown while still displaying my custom dropdown added with the script's after_component() method. Removing the ui() and run() function from my script doesn't do it, and returning False in show() prevents the after_component() method from firing, thus no custom dropdown added.
